Config = {}

Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions

-- Black Market Locations
Config.Locations = {
    [1] = {
        name = "blackmarket1",
        coords = vector4(309.09, -913.75, 29.29, 340.0), -- Downtown alley (example location)
        ped = "g_m_m_chicold_01", -- Scary looking gang member
        scenario = "WORLD_HUMAN_DRUG_DEALER_HARD",
        label = "Black Market Dealer",
        showblip = true, -- Hidden on map
        blipsprite = 500,
        blipscale = 0.7,
        blipcolor = 1,
        products = "blackmarket",
    },
    -- Add more locations as needed
}

-- Products Config
Config.Products = {
    ["blackmarket"] = {
        -- Ammo
        [1] = {
            name = "pistol_ammo",
            price = 500,
            amount = 999,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "rifle_ammo",
            price = 1500,
            amount = 999,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "smg_ammo",
            price = 1000,
            amount = 999,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "shotgun_ammo",
            price = 1000,
            amount = 999,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "mg_ammo",
            price = 2000,
            amount = 999,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "snp_ammo",
            price = 2000,
            amount = 999,
            info = {},
            type = "item",
            slot = 6,
        },
        
        -- Standard Weapons
        [7] = {
            name = "weapon_pistol",
            price = 10000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 7,
        },
        [8] = {
            name = "weapon_combatpistol",
            price = 15000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 8,
        },
        [9] = {
            name = "weapon_smg",
            price = 30000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 9,
        },
        [10] = {
            name = "weapon_assaultrifle",
            price = 50000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 10,
        },
        [11] = {
            name = "weapon_carbinerifle",
            price = 45000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 11,
        },
        
        -- Custom Weapons
        [12] = {
            name = "weapon_ak47",
            price = 60000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 12,
        },
        [13] = {
            name = "weapon_m4",
            price = 55000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 13,
        },
        [14] = {
            name = "weapon_hk416",
            price = 65000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 14,
        },
        [15] = {
            name = "weapon_m110",
            price = 80000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 15,
        },
        [16] = {
            name = "weapon_mp9",
            price = 35000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 16,
        },
        [17] = {
            name = "weapon_mac10",
            price = 32000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 17,
        },
        [18] = {
            name = "weapon_uzi",
            price = 33000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 18,
        },
        [19] = {
            name = "weapon_m9",
            price = 12000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 19,
        },
        [20] = {
            name = "weapon_m1911",
            price = 11000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 20,
        },
        [21] = {
            name = "weapon_de",
            price = 18000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 21,
        },
        [22] = {
            name = "weapon_fnx45",
            price = 13000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 22,
        },
        [23] = {
            name = "weapon_glock17",
            price = 14000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 23,
        },
        [24] = {
            name = "weapon_m70",
            price = 58000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 24,
        },
        [25] = {
            name = "weapon_scarh",
            price = 70000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 25,
        },
        [26] = {
            name = "weapon_mk14",
            price = 85000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 26,
        },
        [27] = {
            name = "weapon_huntingrifle",
            price = 75000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 27,
        },
        [28] = {
            name = "weapon_ar15",
            price = 62000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 28,
        },
        [29] = {
            name = "weapon_mossberg",
            price = 40000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 29,
        },
        [30] = {
            name = "weapon_remington",
            price = 38000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 30,
        },
        [31] = {
            name = "weapon_mp5",
            price = 36000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 31,
        },
        [32] = {
            name = "weapon_glock18c",
            price = 16000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 32,
        },
        [33] = {
            name = "weapon_glock22",
            price = 15000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 33,
        },
        [34] = {
            name = "weapon_ak74",
            price = 61000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 34,
        },
        [35] = {
            name = "weapon_aks74",
            price = 59000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 35,
        },
        [36] = {
            name = "weapon_microsmg",
            price = 28000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 36,
        },
        [37] = {
            name = "weapon_pumpshotgun",
            price = 35000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 37,
        },
        [38] = {
            name = "weapon_sawnoffshotgun",
            price = 30000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 38,
        },
        
        -- Melee Weapons
        [39] = {
            name = "weapon_katana",
            price = 8000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 39,
        },
        [40] = {
            name = "weapon_shiv",
            price = 2000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 40,
        },
        [41] = {
            name = "weapon_sledgehammer",
            price = 5000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 41,
        },
        [42] = {
            name = "weapon_karambit",
            price = 4000,
            amount = 999,
            info = {},
            type = "weapon",
            slot = 42,
        },
        
        -- Pistol Attachments
        [43] = {
            name = "pistol_defaultclip",
            price = 500,
            amount = 999,
            info = {},
            type = "item",
            slot = 43,
        },
        [44] = {
            name = "pistol_extendedclip",
            price = 1000,
            amount = 999,
            info = {},
            type = "item",
            slot = 44,
        },
        [45] = {
            name = "pistol_suppressor",
            price = 3000,
            amount = 999,
            info = {},
            type = "item",
            slot = 45,
        },
        [46] = {
            name = "pistol_flashlight",
            price = 800,
            amount = 999,
            info = {},
            type = "item",
            slot = 46,
        },
        [47] = {
            name = "pistol_luxuryfinish",
            price = 2000,
            amount = 999,
            info = {},
            type = "item",
            slot = 47,
        },
        [48] = {
            name = "combatpistol_defaultclip",
            price = 600,
            amount = 999,
            info = {},
            type = "item",
            slot = 48,
        },
        [49] = {
            name = "combatpistol_extendedclip",
            price = 1100,
            amount = 999,
            info = {},
            type = "item",
            slot = 49,
        },
        [50] = {
            name = "appistol_defaultclip",
            price = 600,
            amount = 999,
            info = {},
            type = "item",
            slot = 50,
        },
        [51] = {
            name = "appistol_extendedclip",
            price = 1100,
            amount = 999,
            info = {},
            type = "item",
            slot = 51,
        },
        [52] = {
            name = "pistol50_defaultclip",
            price = 700,
            amount = 999,
            info = {},
            type = "item",
            slot = 52,
        },
        [53] = {
            name = "pistol50_extendedclip",
            price = 1200,
            amount = 999,
            info = {},
            type = "item",
            slot = 53,
        },
        [54] = {
            name = "snspistol_defaultclip",
            price = 500,
            amount = 999,
            info = {},
            type = "item",
            slot = 54,
        },
        [55] = {
            name = "snspistol_extendedclip",
            price = 900,
            amount = 999,
            info = {},
            type = "item",
            slot = 55,
        },
        [56] = {
            name = "snspistol_grip",
            price = 800,
            amount = 999,
            info = {},
            type = "item",
            slot = 56,
        },
        [57] = {
            name = "heavypistol_defaultclip",
            price = 650,
            amount = 999,
            info = {},
            type = "item",
            slot = 57,
        },
        [58] = {
            name = "heavypistol_extendedclip",
            price = 1150,
            amount = 999,
            info = {},
            type = "item",
            slot = 58,
        },
        [59] = {
            name = "heavypistol_grip",
            price = 900,
            amount = 999,
            info = {},
            type = "item",
            slot = 59,
        },
        [60] = {
            name = "vintagepistol_defaultclip",
            price = 550,
            amount = 999,
            info = {},
            type = "item",
            slot = 60,
        },
        [61] = {
            name = "vintagepistol_extendedclip",
            price = 1000,
            amount = 999,
            info = {},
            type = "item",
            slot = 61,
        },
        
        -- SMG Attachments
        [62] = {
            name = "microsmg_defaultclip",
            price = 800,
            amount = 999,
            info = {},
            type = "item",
            slot = 62,
        },
        [63] = {
            name = "microsmg_extendedclip",
            price = 1500,
            amount = 999,
            info = {},
            type = "item",
            slot = 63,
        },
        [64] = {
            name = "microsmg_scope",
            price = 2000,
            amount = 999,
            info = {},
            type = "item",
            slot = 64,
        },
        [65] = {
            name = "microsmg_luxuryfinish",
            price = 2200,
            amount = 999,
            info = {},
            type = "item",
            slot = 65,
        },
        [66] = {
            name = "smg_defaultclip",
            price = 1000,
            amount = 999,
            info = {},
            type = "item",
            slot = 66,
        },
        [67] = {
            name = "smg_extendedclip",
            price = 2000,
            amount = 999,
            info = {},
            type = "item",
            slot = 67,
        },
        [68] = {
            name = "smg_drum",
            price = 3000,
            amount = 999,
            info = {},
            type = "item",
            slot = 68,
        },
        [69] = {
            name = "smg_suppressor",
            price = 3500,
            amount = 999,
            info = {},
            type = "item",
            slot = 69,
        },
        [70] = {
            name = "smg_scope",
            price = 2500,
            amount = 999,
            info = {},
            type = "item",
            slot = 70,
        },
        [71] = {
            name = "smg_luxuryfinish",
            price = 2400,
            amount = 999,
            info = {},
            type = "item",
            slot = 71,
        },
        [72] = {
            name = "assaultsmg_defaultclip",
            price = 1100,
            amount = 999,
            info = {},
            type = "item",
            slot = 72,
        },
        [73] = {
            name = "assaultsmg_extendedclip",
            price = 2100,
            amount = 999,
            info = {},
            type = "item",
            slot = 73,
        },
        [74] = {
            name = "minismg_defaultclip",
            price = 900,
            amount = 999,
            info = {},
            type = "item",
            slot = 74,
        },
        [75] = {
            name = "minismg_extendedclip",
            price = 1600,
            amount = 999,
            info = {},
            type = "item",
            slot = 75,
        },
        [76] = {
            name = "machinepistol_defaultclip",
            price = 950,
            amount = 999,
            info = {},
            type = "item",
            slot = 76,
        },
        [77] = {
            name = "machinepistol_extendedclip",
            price = 1700,
            amount = 999,
            info = {},
            type = "item",
            slot = 77,
        },
        [78] = {
            name = "machinepistol_drum",
            price = 2800,
            amount = 999,
            info = {},
            type = "item",
            slot = 78,
        },
        [79] = {
            name = "combatpdw_defaultclip",
            price = 1050,
            amount = 999,
            info = {},
            type = "item",
            slot = 79,
        },
        [80] = {
            name = "combatpdw_extendedclip",
            price = 2050,
            amount = 999,
            info = {},
            type = "item",
            slot = 80,
        },
        [81] = {
            name = "combatpdw_drum",
            price = 3100,
            amount = 999,
            info = {},
            type = "item",
            slot = 81,
        },
        [82] = {
            name = "combatpdw_grip",
            price = 1900,
            amount = 999,
            info = {},
            type = "item",
            slot = 82,
        },
        [83] = {
            name = "combatpdw_scope",
            price = 2600,
            amount = 999,
            info = {},
            type = "item",
            slot = 83,
        },
        
        -- Rifle Attachments
        [84] = {
            name = "assaultrifle_defaultclip",
            price = 1500,
            amount = 999,
            info = {},
            type = "item",
            slot = 84,
        },
        [85] = {
            name = "assaultrifle_extendedclip",
            price = 2500,
            amount = 999,
            info = {},
            type = "item",
            slot = 85,
        },
        [86] = {
            name = "assaultrifle_drum",
            price = 4000,
            amount = 999,
            info = {},
            type = "item",
            slot = 86,
        },
        [87] = {
            name = "assaultrifle_luxuryfinish",
            price = 3000,
            amount = 999,
            info = {},
            type = "item",
            slot = 87,
        },
        [88] = {
            name = "carbinerifle_defaultclip",
            price = 1500,
            amount = 999,
            info = {},
            type = "item",
            slot = 88,
        },
        [89] = {
            name = "carbinerifle_extendedclip",
            price = 2500,
            amount = 999,
            info = {},
            type = "item",
            slot = 89,
        },
        [90] = {
            name = "carbinerifle_drum",
            price = 4000,
            amount = 999,
            info = {},
            type = "item",
            slot = 90,
        },
        [91] = {
            name = "carbinerifle_scope",
            price = 3500,
            amount = 999,
            info = {},
            type = "item",
            slot = 91,
        },
        [92] = {
            name = "carbinerifle_luxuryfinish",
            price = 3000,
            amount = 999,
            info = {},
            type = "item",
            slot = 92,
        },
        [93] = {
            name = "advancedrifle_defaultclip",
            price = 1600,
            amount = 999,
            info = {},
            type = "item",
            slot = 93,
        },
        [94] = {
            name = "advancedrifle_extendedclip",
            price = 2600,
            amount = 999,
            info = {},
            type = "item",
            slot = 94,
        },
        [95] = {
            name = "specialcarbine_defaultclip",
            price = 1550,
            amount = 999,
            info = {},
            type = "item",
            slot = 95,
        },
        [96] = {
            name = "specialcarbine_extendedclip",
            price = 2550,
            amount = 999,
            info = {},
            type = "item",
            slot = 96,
        },
        [97] = {
            name = "specialcarbine_drum",
            price = 4100,
            amount = 999,
            info = {},
            type = "item",
            slot = 97,
        },
        [98] = {
            name = "bullpuprifle_defaultclip",
            price = 1550,
            amount = 999,
            info = {},
            type = "item",
            slot = 98,
        },
        [99] = {
            name = "bullpuprifle_extendedclip",
            price = 2550,
            amount = 999,
            info = {},
            type = "item",
            slot = 99,
        },
        [100] = {
            name = "compactrifle_defaultclip",
            price = 1400,
            amount = 999,
            info = {},
            type = "item",
            slot = 100,
        },
        [101] = {
            name = "compactrifle_extendedclip",
            price = 2400,
            amount = 999,
            info = {},
            type = "item",
            slot = 101,
        },
        [102] = {
            name = "compactrifle_drum",
            price = 3900,
            amount = 999,
            info = {},
            type = "item",
            slot = 102,
        },
        [103] = {
            name = "rifle_suppressor",
            price = 5000,
            amount = 999,
            info = {},
            type = "item",
            slot = 103,
        },
        [104] = {
            name = "rifle_flashlight",
            price = 1500,
            amount = 999,
            info = {},
            type = "item",
            slot = 104,
        },
        [105] = {
            name = "rifle_grip",
            price = 2000,
            amount = 999,
            info = {},
            type = "item",
            slot = 105,
        },
        [106] = {
            name = "gusenberg_defaultclip",
            price = 1800,
            amount = 999,
            info = {},
            type = "item",
            slot = 106,
        },
        [107] = {
            name = "gusenberg_extendedclip",
            price = 2800,
            amount = 999,
            info = {},
            type = "item",
            slot = 107,
        },
        
        -- Shotgun Attachments
        [108] = {
            name = "pumpshotgun_luxuryfinish",
            price = 2500,
            amount = 999,
            info = {},
            type = "item",
            slot = 108,
        },
        [109] = {
            name = "sawnoffshotgun_luxuryfinish",
            price = 2200,
            amount = 999,
            info = {},
            type = "item",
            slot = 109,
        },
        [110] = {
            name = "assaultshotgun_defaultclip",
            price = 1700,
            amount = 999,
            info = {},
            type = "item",
            slot = 110,
        },
        [111] = {
            name = "assaultshotgun_extendedclip",
            price = 2700,
            amount = 999,
            info = {},
            type = "item",
            slot = 111,
        },
        [112] = {
            name = "heavyshotgun_defaultclip",
            price = 1800,
            amount = 999,
            info = {},
            type = "item",
            slot = 112,
        },
        [113] = {
            name = "heavyshotgun_extendedclip",
            price = 2800,
            amount = 999,
            info = {},
            type = "item",
            slot = 113,
        },
        [114] = {
            name = "heavyshotgun_drum",
            price = 4200,
            amount = 999,
            info = {},
            type = "item",
            slot = 114,
        },
        [115] = {
            name = "shotgun_suppressor",
            price = 4500,
            amount = 999,
            info = {},
            type = "item",
            slot = 115,
        },
        
        -- Sniper Attachments
        [116] = {
            name = "marksmanrifle_defaultclip",
            price = 2000,
            amount = 999,
            info = {},
            type = "item",
            slot = 116,
        },
        [117] = {
            name = "marksmanrifle_extendedclip",
            price = 3500,
            amount = 999,
            info = {},
            type = "item",
            slot = 117,
        },
        [118] = {
            name = "marksmanrifle_luxuryfinish",
            price = 3200,
            amount = 999,
            info = {},
            type = "item",
            slot = 118,
        },
        [119] = {
            name = "sniper_scope",
            price = 6000,
            amount = 999,
            info = {},
            type = "item",
            slot = 119,
        },
        [120] = {
            name = "snipermax_scope",
            price = 8000,
            amount = 999,
            info = {},
            type = "item",
            slot = 120,
        },
        [121] = {
            name = "heavysniper_scope",
            price = 7500,
            amount = 999,
            info = {},
            type = "item",
            slot = 121,
        },
        [122] = {
            name = "advancedscope",
            price = 9000,
            amount = 999,
            info = {},
            type = "item",
            slot = 122,
        },
    }
}

